### ISSUE TITLE
''Check your internet connection'' error

### ISSUE THREAD

**Issue by Girek250** [wargio/plugin.video.southpark_unofficial#1]
I have a big issue. First i installed plugin and everything worked fine. But after few days i tried to watch random episode and i got ''Error Script Failed!'' followed by ''Check your internet connection''
And this error happens everytime i try to start any episode...
My internet connection is fine and i can load Southpark.cc.com on my web browser so what is the problem?
I reinstalled plugin multiple times and nothing... Still same error... 

What should i do to fix it?

**Comment by wargio** [comment]
did you changed the options? country?

**Comment by Girek250** [comment]
I tried but that still no change...

**Comment by wargio** [comment]
did you changed the options? country?

**Comment by wargio** [comment]
it fails to load the CC..

**Comment by ghuls** [comment]
On Ubuntu 14.04 I was unable to play any episiode.

After looking in the log file, I saw lines like this:
```
19:55:40 T:140626972612352   ERROR: Unable to load librtmp.so.1, reason: librtmp.so.1: cannot open s
hared object file: No such file or directory
```

After installing the following, it worked fine for me:
```
sudo apt-get install librtmp1
```

**Comment by Girek250** [comment]
Thank you! It worked perfectly :)

I switched OS on my laptop to Ubuntu two months ago so you helped me a lot :)

**Comment by wargio** [comment]
oh, that was the problem. ok, then i mark it as closed.

i need to add some checks. it may help.
