### ISSUE TITLE
Add www.southparkstudios.co.uk

### ISSUE THREAD

**Issue by lexieye** [wargio/plugin.video.southpark_unofficial#16]
southpark.cc is not availble in europe but they HAVE just created a https://www.southparkstudios.co.uk/ that is watchable.
i am a die-hard fan of your addon & have noticed the addon no longe working.
i think this is because
(quote) the supported countries are the ones that can view southpark .cc .de .nu

*so* please can you update the script to run from https://www.southparkstudios.co.uk/ server

**Comment by wargio** [comment]
i'll try to add the support this weekend. i have to fix also season 23.

**Comment by wargio** [comment]
i just noticed that all the episodes on southparkstudios.co.uk are not available.
i've added anyway the support, but i do not suggest to use it.

**Comment by wargio** [comment]
Fixed via https://github.com/wargio/plugin.video.southpark_unofficial/commit/3abecabb252e3ec4e02bd50297ffe3f7342e75ac
