### ISSUE TITLE
0.5.4 on Debian buster: python exception

### ISSUE THREAD

**Issue by Malaach** [wargio/plugin.video.southpark_unofficial#17]
Hello,

I'm not really sure if there ist only a folder missing or without appropiate rights, but on a default installation like mine this shouldn't be happening:

> 16:28:31.431 T:139944203306752  NOTICE: Running database version Addons27
> 16:28:31.431 T:139944203306752  NOTICE: Running database version ViewModes6
> 16:28:31.431 T:139944203306752  NOTICE: Running database version Textures13
> 16:28:31.432 T:139944203306752  NOTICE: Running database version MyMusic60
> 16:28:31.433 T:139944203306752  NOTICE: Running database version MyVideos107
> 16:28:31.433 T:139944203306752  NOTICE: Running database version TV29
> 16:28:31.433 T:139944203306752  NOTICE: Running database version Epg11
> 16:28:31.439 T:139944211727104  NOTICE: start dvd mediatype detection
> 16:28:31.552 T:139944211727104 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
> 16:28:31.619 T:139944211727104  NOTICE: initialize done
> 16:28:31.619 T:139944211727104  NOTICE: Running the application...
> 16:28:31.621 T:139944211727104  NOTICE: starting zeroconf publishing
> 16:28:31.621 T:139944211727104  NOTICE: starting upnp client
> 16:28:31.639 T:139942617396992  NOTICE: ES: Starting UDP Event server on port 9777
> 16:28:31.639 T:139942617396992  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
> 16:28:41.433 T:139941359113984   ERROR: GetDirectory - Error getting
> 16:28:41.873 T:139941350721280   ERROR: Previous line repeats 6 times.
> 16:28:41.873 T:139941350721280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.AttributeError'>
>                                             Error Contents: 'xbmcgui.ListItem' object has no attribute 'setIsFolder'
>                                             Traceback (most recent call last):
>                                               File "/home/mopirelli/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 9, in <module>
>                                                 plugin.handle()
>                                               File "/home/mopirelli/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 640, in handle
>                                                 self.create_menu()
>                                               File "/home/mopirelli/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 360, in create_menu
>                                                 self.add_directory(self.i18n.MENU_FEATURED_EPISODES, '', PLUGIN_MODE_FEATURED, self.paths.PLUGIN_ICON)
>                                               File "/home/mopirelli/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 596, in add_directory
>                                                 liz.setIsFolder(True)
>                                             AttributeError: 'xbmcgui.ListItem' object has no attribute 'setIsFolder'
>                                             -->End of Python script error report<--
> 16:28:41.896 T:139944211727104   ERROR: GetDirectory - Error getting plugin://plugin.video.southpark_unofficial/
> 16:28:41.897 T:139944211727104   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.southpark_unofficial/) failed

Could someone please have a look at it and point me into the right direction? TIA!

Malaach

**Comment by Malaach** [comment]
I just saw you already changed something just today for southpark.de - that was the site I intended to use. ;-)

**Comment by wargio** [comment]
which version of kodi do you have?
looks quite old. please use the latest from the kodi website.

**Comment by Malaach** [comment]
Thanks for looking into it! :-)

It's indeed kodi 17.6  from the debian repository as the kodi team advises for debian users. Will look for a newer binary but can't guarantee I can upgrade anytime soon.

Malaach

**Comment by wargio** [comment]
hmm that's weird. krypton is not that old.

**Comment by wargio** [comment]
can you test if https://github.com/wargio/plugin.video.southpark_unofficial/commit/bbe8b608f6d11ef6e4a8ae19872e9ceeec78b0c9 fixes it?

**Comment by Malaach** [comment]
Works!

It tells me "Not available in your country - will be ignored, but be informed" when I open the plugin, but then works normally (I only watched a few seconds). Is this some kind of joke? If so you well deserved a good laugh in me ;-)

Malaach
