### ISSUE TITLE
Python errors since 0.5.2

### ISSUE THREAD

**Issue by nubbery** [wargio/plugin.video.southpark_unofficial#18]
I have an old MyGica Android KitKat box with Kodi 16 (although it was the same story with a beta Lollipop and 17). South Park plugin stopped working since version 0.5.2, immediately crashing saying to check the log. I see that Python 3 support added at 0.5.2. The Kodi log showed:

_IS_PY3 = sys.version_info.major > 2
AttributeError: 'tuple' object has no attribute 'major'_

I searched around the internet and found another way to do it. When I changed the line to:

_IS_PY3 = sys.version_info[0] > 2_

The plugin would now open and everything worked except Season 23. The plugin crashed when opening season 23 folder:

_return "{:02d}d {:02d}h {:02d}m".format(days, hours, mins)
ValueError: zero length field name in format_

Changing the line to the same as 0.5.0 like:

_return "%02dd %02dh %02dm".format(days, hours, mins)_

Allows it to work and play season 23. I'm not familiar with python or many C variants, but I assume the newer style is C# or something and the older python doesn't know what it is?

There are some warnings in the log like "Attempt to use handle 1" but otherwise the plugin works with these 2 changes. Is there a simple way to accommodate the older platform?

**Comment by wargio** [comment]
Can you test this? https://github.com/wargio/plugin.video.southpark_unofficial/archive/0.5.6.zip

**Comment by nubbery** [comment]
Works. Thank you!

**Comment by wargio** [comment]
ok, let me merge it and patch it globally

**Comment by nubbery** [comment]
I checked it on Windows with Kodi 18 to make sure it didn't break anything somehow. Works fine. Thanks again.

**Comment by wargio** [comment]
https://github.com/xbmc/repo-plugins/pull/2559
