### ISSUE TITLE
Please add support for www.southpark.lat

### ISSUE THREAD

**Issue by IPeluchito** [wargio/plugin.video.southpark_unofficial#30]
Please add support for www.southpark.lat here the audio is in Spanish directly ...

Thanks in advance...

**Comment by wargio** [comment]
from which country is that from?

**Comment by IPeluchito** [comment]
According to **domaintools**:

![Captura](https://user-images.githubusercontent.com/64821708/95918025-b8089300-0d70-11eb-8bb9-b5c70e16aaa0.PNG)

The audio from www.southpark.lat is **Latin Spanish**.

**Comment by wargio** [comment]
https://github.com/wargio/plugin.video.southpark_unofficial/issues/38
