### ISSUE TITLE
[DE] addon-data-de.json not enough entries

### ISSUE THREAD

**Issue by NeonGreenLemon** [wargio/plugin.video.southpark_unofficial#31]
pluginversion 0.6.2

location: de
language: de

There are only the first 10 episodes of each season visible the others aren't loaded.

I think the issue is in the addon-data-de.json since there are only 10 episodes listed for each season

[addon-data-de.json](https://raw.githubusercontent.com/wargio/plugin.video.southpark_unofficial/addon-data/addon-data-de.json)

Thank you!

**Comment by wargio** [comment]
thank you for the update. i'll check it immediately :)

**Comment by wargio** [comment]
please @NeonGreenLemon clear the cache `.kodi/temp/southpark` and tell me if everything feels correct. i have fixed a small issue i had with the german data.

**Comment by NeonGreenLemon** [comment]
looks like it works!

Thank you
