### ISSUE TITLE
SP Not working - No episodes playing

### ISSUE THREAD

**Issue by Elzama** [wargio/plugin.video.southpark_unofficial#32]
Hey everyone!

First and foremost, thanks for the awesome app.  Now to the issue... I updated the app to the newest v, but it stopped working again, just like 0.6.0 

I am using Kodi 18.8

I am not seeing anything on the logs. 

Thanks again!

**Comment by wargio** [comment]
@Elzama can you tell me from which country you are connecting from and which are your settings?

**Comment by Elzama** [comment]
Hi dev! 
I am trying to watch from Japan.  My settings are as follows:
Audio Language: EN
Geo Loc:  US

Once I open the app, I go into any season and it just wont load any episodes.  It says to check the log.  I go to my kodi settings to check the logs but nothing shows up for South Park.

**Comment by Elzama** [comment]
Pic 
![CB4DD761-12C3-493F-A521-65CD9AC742C5](https://user-images.githubusercontent.com/51191202/96131741-8c360a80-0f34-11eb-8eda-7fd25a2179fd.jpeg)

**Comment by wargio** [comment]
clear your cache.

**Comment by Elzama** [comment]
Thank you!  That fixed it!
I appreciate the help!

**Comment by Elzama** [comment]
Just to reopen, no episodes from season 1 - 23 are playing.  Only the latest season. 
My settings have not changed (same as OP)

**Comment by wargio** [comment]
it's useless to have multiple issues on the same subject.
