### ISSUE TITLE
Frozen stream

### ISSUE THREAD

**Issue by lexieye** [wargio/plugin.video.southpark_unofficial#37]
I have a pi 3B + .
Latest updated Kodi with the standard RetroPie install
No problem with the api and the interface of Kodi with your addon.
It’s when I play any of your streams, I first get an advert (like the South Park website) but it gets stuck on the last frame of the advert!
I can hear the video of the South Park Episode playing in the background but only see the last frame of the previous  advert! When the next advert comes on again after 4 minutes of part one of that episode, I get full HD video of the advert but then when it starts playing part 2 of the same episode, it’s back to the last frame of that Next Advert

I’m not sure if it’s a pi thing or your addon.
I hope you or someone can share if they have a similar problem

**Comment by wargio** [comment]
dup: https://github.com/wargio/plugin.video.southpark_unofficial/issues/33#issuecomment-725774898
