### ISSUE TITLE
Please add support for www.southparkstudios.com.br

### ISSUE THREAD

**Issue by MfskBR** [wargio/plugin.video.southpark_unofficial#39]
Please add support for www.southparkstudios.com.br here the audio is in brazilian portuguese...

Thanks in advance...

**Comment by serajr** [comment]
@wargio I've added brazilian pt-br support (pt-br commits), and everything's working great!

@MfskBR for now, download Source code (zip) and install it on Kodi:
https://github.com/serajr/plugin.video.southpark_unofficial/releases/tag/v1.0.0_pt-br

**Comment by wargio** [comment]
@serajr can you open a PR? on both branches. i'll push this on the kodi repo

**Comment by MfskBR** [comment]
> @wargio I've added brazilian pt-br support (pt-br commits), and everything's working great!
> 
> @MfskBR for now, download Source code (zip) and install it on Kodi (also change localization to: Brasil).
> https://github.com/serajr/plugin.video.southpark_unofficial/releases/tag/v1.0.0_pt-br

Ok, I downloaded the zip and installed it on kodi without problems, so far it works fine.

**Comment by wargio** [comment]
Added. I'll push the update in the day. hopefully in 1 or 2 days it should be live.

**Comment by wargio** [comment]
https://github.com/xbmc/repo-plugins/pull/3666

**Comment by serajr** [comment]
> @serajr can you open a PR? on both branches. i'll push this on the kodi repo
You were faster than me, mate. Keep up the great work!
Btw, Kodi [repo](https://kodi.wiki/view/Add-on:South_Park) still showing version old version.
