### ISSUE TITLE
Playback Fail

### ISSUE THREAD

**Issue by fijimouse** [wargio/plugin.video.southpark_unofficial#4]
I am unable to play any of the episodes due to "bad internet connection" even though I am able to download and stream other add ons. I've tried updating and redownloading the add on, but it still does no good.

**Comment by wargio** [comment]
fixed.

**Comment by PanderMusubi** [comment]
Could you please bump http://addons.kodi.tv/show/plugin.video.southpark_unofficial/ to version 0.4.5? Thanks

**Comment by PanderMusubi** [comment]
It work, thanks
