### ISSUE TITLE
Problem Season 14 and 15 also conflict with InputStream Adaptive addon

### ISSUE THREAD

**Issue by SmokeyBR** [wargio/plugin.video.southpark_unofficial#42]
ive been meaning to open an issue about this but never really had the time for it.

Geo Location: North America[EN]
Enable CC: ON
Play directly the random episode: OFF
Clear Cache: Has been tested
My Location: Brazil

Seasons 14 and 15 which are seasons that don't have the entire opening scene just a southpark logo with all the characters in the back, all the videos in it will get stuck on that logo however sound will continue to play normally.

i also use the addon "VideoPlayer InputStream - InputStream Adaptive" if its enabled southpark episodes wont play until you disable it, kodi log when trying to play southpark with addon enabled: https://pastebin.com/QNTzYCjh

**Comment by alexfd** [comment]
For me most seasons won't play anymore (besides s24) when InputStream Adaptive plugin is active. After I disable it, they start working. The bad part is I need this plugin for another video service.
Is there a way to force this plugin to not use InputStream Adaptive if active?

**Comment by wargio** [comment]
try to delete these 2 lines: https://github.com/wargio/plugin.video.southpark_unofficial/blob/master/southpark.py#L444

**Comment by alexfd** [comment]
Awesome, it worked. Thanks!

**Comment by wargio** [comment]
This should be fixed with the next update: https://github.com/xbmc/repo-plugins/pull/3666
