### ISSUE TITLE
Include support to pt-BR

### ISSUE THREAD

**Issue by RodrigoWantuk** [wargio/plugin.video.southpark_unofficial#44]
Please, include support to pt-BR website on your json repos.

The episodes can be accessed by: https://www.southparkstudios.com.br/seasons/south-park

**Comment by serajr** [comment]
> Please, include support to pt-BR website on your json repos.
> 
> The episodes can be accessed by: https://www.southparkstudios.com.br/seasons/south-park

https://github.com/wargio/plugin.video.southpark_unofficial/issues/39#issuecomment-873625236

**Comment by wargio** [comment]
Added. once i push the latin america one, then i will push an update to the kodi plugin list.

**Comment by wargio** [comment]
https://github.com/xbmc/repo-plugins/pull/3666
