### ISSUE TITLE
Video Freezes during the transition from ad to video.

### ISSUE THREAD

**Issue by Nayr438** [wargio/plugin.video.southpark_unofficial#45]
System -> Raspberry Pi 4 4GB
OS/Kodi-> Librelec 9.2.7 (Kodi 18.9), LibreElec 9.95.4 (Matrix/v19.0), Arch Arm kodi-rpi (gbm_matrix fork)

Anytime a Advertisement plays at the beginning of a video it gets stuck during the transition process, usually on the ad such as a Nissan Commercial or the Comedy Central Logo, sometimes it makes it to the video itself and immediately freezes. The Audio however continues to play as if everything was normal. This happens regardless of what Region Settings are used.

**Comment by wargio** [comment]
known bug which i can't fix.
