### ISSUE TITLE
Pandemic special german is playing english version

### ISSUE THREAD

**Issue by eloo** [wargio/plugin.video.southpark_unofficial#53]
Hi,

i have just figured out that the pandemic special german (last episode of season 23 is working in german) is playing the english version instead of the german one.

For german only the first special is available while for english the also the second is available.
Also the title in german is correct. so i guess the changing of the language/country is working.
But anyhow the wrong episode is played.

Thanks

**Comment by wargio** [comment]
thanks, i will re-generate the episode data.

**Comment by wargio** [comment]
@eloo please, clear the cache and let me know if it works correctly. if yes, please close this issue.

**Comment by eloo** [comment]
@wargio i can confirm that its working for german now 👍
