### ISSUE TITLE
first sec of each part is gone

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [wargio/plugin.video.southpark_unofficial#6]
hey there. THX a lot for your great kodi addon.

Since some month (I think 5 or more), I had issues with each german episode. It begins with the first seconds, they are gone. Then within each episode this happen'd again.

I think each episode is parted into 3 or 4 parts, to send ad's online to the viewers and I think the addon had some problems with the first seconds of each track.

Does I am alone with this problem?

by uniat

**Comment by wargio** [comment]
i'll check if this behaviour is a problem of the plugin or something directly linked to Kodi.
There is a known issue where the new Kodi does a bad job on those HSL streams where it froze for a few seconds and then you will miss a few second at the beginning of the ep.

**Comment by SkyBird1980** [comment]
Issue is still open and related to another problem:
if you start an episode "busy arrow" is visible forever.
if you press now escape the episode stops (audio is playing) and video goes fast forward to the current position. After playing the episode and if you wait for the screensaver the video will start again.

**Comment by wargio** [comment]
i've pushed an update. i hope within the next days to be pushed on the official repo.
once you see the new version, can you try again?

**Comment by SkyBird1980** [comment]
I just download your zip and update now^^ easy.

**Comment by SkyBird1980** [comment]
Fixed!

**Comment by wargio** [comment]
ok, i'll close this issue. :D
