### ISSUE TITLE
Feature-Request Play random episode via jsonrpc

### ISSUE THREAD

**Issue by mrchainman** [wargio/plugin.video.southpark_unofficial#62]
I don't know if this is already possible with the addon, if so could you provide an example?
I'd like to be able to send a jsonrpc request to kodi to start playing a random episode.
This would be useful to automate it with homeassistant for example.

Thanks

**Comment by wargio** [comment]
there is a custom path on the plugin which returns a random episode and based on the configuration can be auto-played.

**Comment by mrchainman** [comment]
Thanks for the quick reposnse, play random directly is set to true, I just can't figure out the right path.
-d '{"jsonrpc": "2.0", "method": "Player.Open", "params": { "item": { "file": "plugin://plugin.video.southpark_unofficial/????" } }, "id": 1 }' \
Where I put ???? in the path, what should go there? I tried putting in "random", "playrandom" but I get errors saying ERROR <general>: [sp.addon] strptime() argument 0 must be str, not <class 'list'>
So apparently I am not calling it directly

**Comment by wargio** [comment]
i think is `plugin://plugin.video.southpark_unofficial?mode=sp:random` you can easily verify this by reading the logs after selecting from the menu the random option

**Comment by mrchainman** [comment]
Awesome! works!
Thanks very much, issue can be closed :)
