### ISSUE TITLE
Feature Request: Set Addon Handle

### ISSUE THREAD

**Issue by s1kk** [wargio/plugin.video.southpark_unofficial#7]
Hey! First of all I wanted to say thank you for the well working addon. I have a Feature Request or also an improvement idea for this addon. Currently I am using various addons for stream videos from 3rd party streaming sites like Netflix or Exodus. These addons are using the addon_handle function by the Kodi API which make them browseable through the existing library. This is not supported by this South Park addon atm.

If you integrate something like this xbmcplugin.setContent(addon_handle, 'episodes') to the default.py it would be possible to add the whole South Park addon as TV Show in the Library. Referencing to: https://kodi.wiki/view/Audio-video_add-on_tutorial 

Thank you!

**Comment by wargio** [comment]
I didn't know about this.
I'll try to add this feature, this weekend.
