### ISSUE TITLE
Feature Request: Add southparkstudios.nu

### ISSUE THREAD

**Issue by ghost** [wargio/plugin.video.southpark_unofficial#8]
It would be extremely useful for me since I live in Sweden and southparkstudios.nu is the only legal way to stream South Park episodes in Sweden.

**Comment by wargio** [comment]
oh. i didn't know its existence. good to know.

**Comment by wargio** [comment]
once merged i'll close this issue too: https://github.com/xbmc/repo-plugins/pull/2526

**Comment by wargio** [comment]
merged.
